name: eznlp_tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: python setup.py install
      - name: Test
        run: | #todo: complete
          echo Add other actions to build,
          echo test, and deploy your project.