name: eznlp_tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: pip install git+https://github.com/dpinney/eznlp
      - name: Test
        run: python -c 'import eznlp; eznlp._run_all_tests()'